### PR TITLE
Add automatic dummy file creation

### PR DESCRIPTION
**Pull request by Epicpkmn11**
- This makes a dummy file to fix the launcher bug be generated automatically on boot if needed
- Also switches to libslim so the dummy file can be a sparse file

---

- Tested on DSi LL (J) with the latest Unlaunch

### CODE REVIEW

**Comment by chyyran** [comment]
Try `truncate` or `ftruncate` instead of fseek + fput

**Comment by Epicpkmn11** [comment]
> Try `truncate` or `ftruncate` instead of fseek + fput

`truncate` doesn't seem to do anything if the file doesn't already exist, is that intended?
And I'm not sure how to use `ftruncate`...

Edit: using libslim 4728966, the current master

**Comment by chyyran** [comment]
> > Try `truncate` or `ftruncate` instead of fseek + fput
> 
> `truncate` doesn't seem to do anything if the file doesn't already exist, is that intended?
> And I'm not sure how to use `ftruncate`...
> 
> Edit: using libslim 4728966, the current master

Ok, this seems to be a bug although both behaviours are POSIX-compliant, I would like `truncate` to be able to extend the file.

> The details in DESCRIPTION are for XSI-compliant systems. For non-XSI-compliant systems, the POSIX standard allows two behaviors for ftruncate() when length exceeds the file length (note that truncate() is not specified at all in such an environment): either returning an error, or extending the file. Like most UNIX implementations, Linux follows the XSI requirement when dealing with native file systems. However, some nonnative file systems do not permit truncate() and ftruncate() to be used to extend a file beyond its current length: a notable example on Linux is VFAT.

> https://linux.die.net/man/2/ftruncate

Will fix in a bit.

**Comment by chyyran** [comment]
> > Try `truncate` or `ftruncate` instead of fseek + fput
> 
> `truncate` doesn't seem to do anything if the file doesn't already exist, is that intended?
> And I'm not sure how to use `ftruncate`...
> 
> Edit: using libslim 4728966, the current master

Oh I misread your comment. Yeah the file needs to be open and created.

**Pull request merged**
